apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: secrets-example
spec:
  provider: aws
  parameters:
    objects: |
      - objectName: secrets-example
        objectType: secretsmanager
        objectAlias: .secret
      - objectName: super-secret-example
        objectType: secretsmanager
        objectAlias: .super-secret
      
